name: yumemi-ios-training

options:
  bundleIdPrefix: com.tdk0105
  deploymentTarget:
    iOS: 14.4
  developmentLanguage: ja
  xcodeVersion: "12.4"

packages:
  YumemiWeather:
    url: https://github.com/yumemi-inc/ios-training.git
    version: 1.0.3
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    version: 1.8.2
targets:
  yumemi-ios-training:
    type: application
    platform: iOS
    sources:
      - yumemi-ios-training
    settings:
      base:
        INFOPLIST_FILE: yumemi-ios-training/Info.plist
    dependencies:
      - package: YumemiWeather
        
  yumemi-ios-trainingTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - yumemi-ios-trainingTests
    settings:
      base:
        INFOPLIST_FILE: yumemi-ios-trainingTests/Info.plist
    dependencies:
      - target: yumemi-ios-training
      - package: SnapshotTesting
    preBuildScripts:
      - path: ./Scripts/XcodeGen/mockolo.sh
        name: Generate Mocks with Mockolo

  yumemi-ios-trainingUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - yumemi-ios-trainingUITests
    settings:
      base:
        INFOPLIST_FILE: yumemi-ios-trainingUITests/Info.plist
    dependencies:
      - target: yumemi-ios-training

schemes:
  yumemi-ios-training:
    build:
      targets:
        yumemi-ios-training: all
    run:
      config: Debug
      environmentVariables:
        - variable: SNAPSHOT_ARTIFACTS
          value: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/__Snapshots__/Failure
          isEnabled: true
    test:
      config: Debug
      targets: 
        - name: yumemi-ios-trainingTests
          randomExecutionOrder: true
          parallelizable: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
