name: yumemi-ios-training

options:
  bundleIdPrefix: com.tdk0105
  deploymentTarget:
    iOS: 14.4
  developmentLanguage: ja
  xcodeVersion: "12.4"

settings:
  configs:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf"

packages:
  YumemiWeather:
    url: https://github.com/yumemi-inc/ios-training.git
    version: 1.0.3

targets:
  yumemi-ios-training:
    type: application
    platform: iOS
    sources:
      - yumemi-ios-training
    settings:
      base:
        INFOPLIST_FILE: yumemi-ios-training/Info.plist
        DEVELOPMENT_LANGUAGE: jp
    dependencies:
      - package: YumemiWeather
        
  yumemi-ios-trainingTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - yumemi-ios-trainingTests
    settings:
      base:
        INFOPLIST_FILE: yumemi-ios-trainingTests/Info.plist
    dependencies:
      - target: yumemi-ios-training

  yumemi-ios-trainingUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - yumemi-ios-trainingUITests
    settings:
      base:
        INFOPLIST_FILE: yumemi-ios-trainingUITests/Info.plist
    dependencies:
      - target: yumemi-ios-training

schemes:
  yumemi-ios-training:
    build:
      targets:
        yumemi-ios-training: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
