name: yumemi-ios-training

options:
  bundleIdPrefix: com.tdk0105
  deploymentTarget:
    iOS: 14.4
  developmentLanguage: ja
  xcodeVersion: "12.4"

packages:
  YumemiWeather:
    url: https://github.com/yumemi-inc/ios-training.git
    version: 1.0.3
targets:
  yumemi-ios-training:
    type: application
    platform: iOS
    sources:
      - yumemi-ios-training
    settings:
      base:
        INFOPLIST_FILE: yumemi-ios-training/Info.plist
    dependencies:
      - package: YumemiWeather
        
  yumemi-ios-trainingTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - yumemi-ios-trainingTests
      - path: "yumemi-ios-trainingTests/Generated/MockResults.swift"
        optional: true
        createIntermediateGroups: true
    settings:
      base:
        INFOPLIST_FILE: yumemi-ios-trainingTests/Info.plist
    dependencies:
      - target: yumemi-ios-training
    preBuildScripts:
      - path: ./Scripts/XcodeGen/mockolo.sh
        name: Generate Mocks with Mockolo
        outputFiles:
          - yumemi-ios-trainingTests/Generated/MockResults.swift

  yumemi-ios-trainingUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - yumemi-ios-trainingUITests
    settings:
      base:
        INFOPLIST_FILE: yumemi-ios-trainingUITests/Info.plist
    dependencies:
      - target: yumemi-ios-training

schemes:
  yumemi-ios-training:
    build:
      targets:
        yumemi-ios-training: all
    run:
      config: Debug
    test:
      config: Debug
      targets: 
        - name: yumemi-ios-trainingTests
          randomExecutionOrder: true
          parallelizable: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
